spring.application.name=cash-tracker
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=classpath:/static/
spring.jpa.open-in-view=false
spring.security.filter.order=10
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VuIGdlbmVyYXRpb24h
jwt.expiration=86400000
# App port
server.port=8080
