spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET:devonlysecretchangemeplease1234567890jdfhhgghurr784747474fg4f74gfh447f4hf4hf7f474hfhfhf}
